---
- name: Playbook with tags
  hosts: planetexpress

  vars:
    cargo1: "prizes for claw crane"
    cargo2: "popcorn"
    cargo3: "pillows"

  vars_files:
    - /home/student/ans/vars/vars.yml

  tasks:
    - name: "depliy ordre to crew"
      template:
         src: /home/student/ans/templates/orders.txt.j2
         dest: ~/orders.txt
      tags:
        - orders

    - name: "deploy manifest"
      template:
        src: /home/student/ans/templates/cargo_manifest.txt.j2
        dest: ~/cargo_manifest.txt
      tags:
        - cargo
        - ship_prep

    - name: "install charts"
      template:
        src: /home/student/ans/templates/navigation_charts.cfg.j2
        dest: ~/navigation_charts.cfg
      tags:
        - nav
        - ship_prep
