---
- name: play with tags
  hosts: planetexpress

  vars:
          - fileloc: "/var/log/bootstrap.log"

  tasks:
          - name: "Insert a line into {{ fileloc }}"
            replace:
                    path: "{{ fileloc }}"
                    regexp: "^Setting up lib.*"
                    replace: "REDACTED BY ANSIBLE lineinfile module"
                    backup: yes
            become: true
