---
- name : learning to recall var data
  hosts: localhost
  connection: local

  vars:
    telecom:
      - ericsson
      - alu
      - avaya
      - nokia
      - cisco
    heroes:
      marvel:
        - spiderman
        - ironman
        - daredevil
      dc:
        - wonderman
        - batman
        - superman

  tasks:
    - name: print out spiderman
      debug:
        msg: "{{ heroes.marvel[0] }}"

    - name: print out batman
      debug:
        msg: "{{ heroes.dc[1] }}"

    - name: print out cisco
      debug:
        msg: "{{ telecom[4] }}"

    - name: print all
      debug:
        msg: "{{ item }}"
      loop: "{{ heroes.marvel + heroes.dc }}"

