---
- name: Our first play
  hosts: planetexpress
  gather_facts: yes 

  tasks:
    - name: Install ALL machines
      apt:
        name: sl
        state: present
      become: yes
      when: ansible_distribution == "Ubuntu"
