---
- name: Copying
  hosts: planetexpress:!farnsworth
  gather_facts: yes

  tasks:
    - name: Copy
      copy:
        content: "{{ ansible_all_ipv4_addresses }}"
        dest: ~/ipv4info.txt
        backup: yes
        force: yes
